version: "3.7"

services:
  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - /opt/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - sonarqube

  sonarqube:
    image: sonarqube:8.2-community
    depends_on:
      - db
    env_file: 
      - .env
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    deploy:
      resources:
        limits:
          memory: 4000M
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  postgresql:
  postgresql_data: